version: '3.7'

services:
  app:
    build:
      context: .
    volumes:
      - .:/smartphone_store
    ports:
      - '3001:3001'
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/smartphone_store
    tty: true
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - ../temp/db/:/var/lib/postgresql/data
